package iuh.labbooking.enums;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELED,
    BOOKING_CANCELLED_BY_THESIS,
    PARTICIPANT_CONFLICT_REQUIRED,
    PARTICIPANT_CONFLICT_RESOLVED,
    THESIS_PARTICIPANT_ADDED
}
